config/routes.rb
Rails.application.routes.draw do
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'

  resources :choices
  resources :results
  resources :records
  get 'exams/create'
  post 'exams/create'

  resources :exams
  resources :questions
  resources :fields
  resources :subjects
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'


  get 'exams/create'
  post 'exams/create'
  get 'exams/show'
  get 'exams/delete'
  post 'exams/delete'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #メニュー画面
  get 'select', to: 'select#menu'

  #理科ボタン
  get 'select/science'
  post 'select/science'

  #社会ボタン
  get 'select/social_study'
  post 'select/social_study'

  #分野選択画面
  get 'select/select'

  get 'exams/create', to: 'exams#create'
  post 'exams/create', to: 'exams#create'

  get 'exams/choice'
  post 'exams/choice'

  get 'exams/answer'
  post 'exams/answer'


  get 'exams/:id', to: 'exams#show'
  post 'exams/:id', to: 'exams#show', as: 'next'

  post 'select/test'

end

app/models/choice.rb
class Choice < ApplicationRecord
belongs_to :question
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: %i[ show edit update destroy ]

  # GET /choices or /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1 or /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices or /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to choice_url(@choice), notice: "Choice was successfully created." }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1 or /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to choice_url(@choice), notice: "Choice was successfully updated." }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1 or /choices/1.json
  def destroy
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to choices_url, notice: "Choice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def choice_params
      params.require(:choice).permit(:choice_no, :choice, :answer, :question_id)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_choice.html.erb
<div id="<%= dom_id choice %>">
  <p>
    <strong>Choice no:</strong>
    <%= choice.choice_no %>
  </p>

  <p>
    <strong>Choice:</strong>
    <%= choice.choice %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= choice.answer %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= choice.question_id %>
  </p>

</div>

app/views/choices/_form.html.erb
<%= form_with(model: choice) do |form| %>
  <% if choice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
        <% choice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :choice_no, style: "display: block" %>
    <%= form.number_field :choice_no %>
  </div>

  <div>
    <%= form.label :choice, style: "display: block" %>
    <%= form.text_area :choice %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.check_box :answer %>
  </div>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.number_field :question_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render "form", choice: @choice %>

<br>

<div>
  <%= link_to "Show this choice", @choice %> |
  <%= link_to "Back to choices", choices_path %>
</div>

app/views/choices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Choices</h1>

<div id="choices">
  <% @choices.each do |choice| %>
    <%= render choice %>
    <p>
      <%= link_to "Show this choice", choice %>
    </p>
  <% end %>
</div>

<%= link_to "New choice", new_choice_path %>

app/views/choices/new.html.erb
<h1>New choice</h1>

<%= render "form", choice: @choice %>

<br>

<div>
  <%= link_to "Back to choices", choices_path %>
</div>

app/views/choices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @choice %>

<div>
  <%= link_to "Edit this choice", edit_choice_path(@choice) %> |
  <%= link_to "Back to choices", choices_path %>

  <%= button_to "Destroy this choice", @choice, method: :delete %>
</div>