config/routes.rb
Rails.application.routes.draw do
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'

  resources :choices
  resources :results
  resources :records
  get 'exams/create'
  post 'exams/create'

  resources :exams
  resources :questions
  resources :fields
  resources :subjects
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'


  get 'exams/create'
  post 'exams/create'
  get 'exams/show'
  get 'exams/delete'
  post 'exams/delete'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #メニュー画面
  get 'select', to: 'select#menu'

  #理科ボタン
  get 'select/science'
  post 'select/science'

  #社会ボタン
  get 'select/social_study'
  post 'select/social_study'

  #分野選択画面
  get 'select/select'

  get 'exams/create', to: 'exams#create'
  post 'exams/create', to: 'exams#create'

  get 'exams/choice'
  post 'exams/choice'

  get 'exams/answer'
  post 'exams/answer'


  get 'exams/:id', to: 'exams#show'
  post 'exams/:id', to: 'exams#show', as: 'next'

  post 'select/test'

end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: %i[ show edit update destroy ]

  # GET /results or /results.json
  def index
    @results = Result.all
  end

  # GET /results/1 or /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results or /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to result_url(@result), notice: "Result was successfully created." }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1 or /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to result_url(@result), notice: "Result was successfully updated." }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1 or /results/1.json
  def destroy
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url, notice: "Result was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def result
    record = Record.where(user_id: current_user.user_id).last
    record_id = record.id
    @result = Result.where(record_id: record_id)

    @right = Result.where(record_id: record_id, user_answer: true)  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def result_params
      params.require(:result).permit(:record_id, :question_id, :user_answer)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result) do |form| %>
  <% if result.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
        <% result.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :record_id, style: "display: block" %>
    <%= form.number_field :record_id %>
  </div>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.number_field :question_id %>
  </div>

  <div>
    <%= form.label :user_answer, style: "display: block" %>
    <%= form.check_box :user_answer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/results/_result.html.erb
<div id="<%= dom_id result %>">
  <p>
    <strong>Record:</strong>
    <%= result.record_id %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= result.question_id %>
  </p>

  <p>
    <strong>User answer:</strong>
    <%= result.user_answer %>
  </p>

</div>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render "form", result: @result %>

<br>

<div>
  <%= link_to "Show this result", @result %> |
  <%= link_to "Back to results", results_path %>
</div>

app/views/results/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Results</h1>

<div id="results">
  <% @results.each do |result| %>
    <%= render result %>
    <p>
      <%= link_to "Show this result", result %>
    </p>
  <% end %>
</div>

<%= link_to "New result", new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render "form", result: @result %>

<br>

<div>
  <%= link_to "Back to results", results_path %>
</div>

app/views/results/result.html.erb
<h3>今回の成績</h3>
<% i = 0 %>
<table>
<% @result.each do |r| %>
    <% i += 1 %>
      <tr>
        <td><%= i %></td>
        <td><%= Question.find_by(id: r.question_id).sentence %></td>
      <% if r.user_answer %>
        <td>〇</td>
      <% else %>
        <td>×</td>
      <% end %>
      </tr>
<% end %>
</table>

<p><%= @right.count %> / <%= @result.count %></p>
<p><%= (@right.count.to_f / @result.count * 100).to_i %> %</p>

<p><a href='/select'>メニュー</a></p>

app/views/results/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @result %>

<div>
  <%= link_to "Edit this result", edit_result_path(@result) %> |
  <%= link_to "Back to results", results_path %>

  <%= button_to "Destroy this result", @result, method: :delete %>
</div>