config/routes.rb
Rails.application.routes.draw do
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'

  resources :choices
  resources :results
  resources :records
  get 'exams/create'
  post 'exams/create'

  resources :exams
  resources :questions
  resources :fields
  resources :subjects
  post 'seiseki/index'
  get 'seiseki/:id', to: 'seiseki#detail'
  post 'seiseki/:id', to: 'seiseki#detail'

  get 'results/result'


  get 'exams/create'
  post 'exams/create'
  get 'exams/show'
  get 'exams/delete'
  post 'exams/delete'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #メニュー画面
  get 'select', to: 'select#menu'

  #理科ボタン
  get 'select/science'
  post 'select/science'

  #社会ボタン
  get 'select/social_study'
  post 'select/social_study'

  #分野選択画面
  get 'select/select'

  get 'exams/create', to: 'exams#create'
  post 'exams/create', to: 'exams#create'

  get 'exams/choice'
  post 'exams/choice'

  get 'exams/answer'
  post 'exams/answer'


  get 'exams/:id', to: 'exams#show'
  post 'exams/:id', to: 'exams#show', as: 'next'

  post 'select/test'

end

app/models/field.rb
class Field < ApplicationRecord
    belongs_to :subject
    has_many :question
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: %i[ show edit update destroy ]

  # GET /fields or /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1 or /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields or /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to field_url(@field), notice: "Field was successfully created." }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1 or /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to field_url(@field), notice: "Field was successfully updated." }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1 or /fields/1.json
  def destroy
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url, notice: "Field was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def field_params
      params.require(:field).permit(:subject_id, :field_name)
    end
end

app/helpers/field_helper.rb
module FieldHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field.html.erb
<div id="<%= dom_id field %>">
  <p>
    <strong>Subject:</strong>
    <%= field.subject_id %>
  </p>

  <p>
    <strong>Field  name:</strong>
    <%= field.field_name %>
  </p>

</div>

app/views/fields/_form.html.erb
<%= form_with(model: field) do |form| %>
  <% if field.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
        <% field.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :subject_id, style: "display: block" %>
    <%= form.number_field :subject_id %>
  </div>

  <div>
    <%= form.label :field_name, style: "display: block" %>
    <%= form.text_area :field_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render "form", field: @field %>

<br>

<div>
  <%= link_to "Show this field", @field %> |
  <%= link_to "Back to fields", fields_path %>
</div>

app/views/fields/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fields</h1>

<div id="fields">
  <% @fields.each do |field| %>
    <%= render field %>
    <p>
      <%= link_to "Show this field", field %>
    </p>
  <% end %>
</div>

<%= link_to "New field", new_field_path %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render "form", field: @field %>

<br>

<div>
  <%= link_to "Back to fields", fields_path %>
</div>

app/views/fields/select_field.html.erb
<h1>分野</h1>

app/views/fields/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @field %>

<div>
  <%= link_to "Edit this field", edit_field_path(@field) %> |
  <%= link_to "Back to fields", fields_path %>

  <%= button_to "Destroy this field", @field, method: :delete %>
</div>